### ISSUE TITLE
Problem writing config files

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/tugboat#9]
I just tried twice to create a new Demo site on BackdropCMS Tugboat and both times, I was unable to write any config files. 

Initially, I was trying to edit the home page layout and got this message:

Failed to write configuration file: ./files/config_5bdcabd9c299f0000169ff24/active/layout.layout.home.json

I also tried creating a new content type and got this message:

Failed to write configuration file: ./files/config_5bdcabd9c299f0000169ff24/active/user.role.anonymous.json

I assume that the site is not able to write to any config files at the moment.

**Comment by ghost** [comment]
Working on this...

**Comment by ghost** [comment]
Ok, think I fixed it. My PR against the https://github.com/backdrop-ops/backdrop-tugboat repo does the following:

- Changes most references of `${DOCROOT}` to `${TUGBOAT_ROOT}` (since the former is a symlink to the latter, it shouldn't matter, but I think making permissions, etc. changes to the real directory instead of the symlink seems to work better/more consistently).
- Removes the line `chown -R www-data:www-data "${DOCROOT}/files"` (since it's covered by the next line `chown -R www-data:www-data "${TUGBOAT_ROOT}"` anyway)
- Changes setting new permissions on *all* files/folders to just those in the the `files`, `layouts`, `modules` and `themes` directories (the problem was that it was un-setting the executable tag on script files)
- Add new code after the install to fix the permissions on the active config directory (which for some reason were being reverted to `root` user and no write permissions for the group (bug report: https://github.com/backdrop/backdrop-issues/issues/4348))

**Comment by ghost** [comment]
Committed PR.

**Comment by stpaultim** [comment]
Works for me! Thanks @BWPanda
